export enum Key {
  Backspace = "Backspace",
  Tab = "Tab",
  Enter = "Enter",
  Shift = "Shift",
  Ctrl = "Ctrl",
  Cmd = "Cmd",
  CmdOrCtrl = "CmdOrCtrl",
  Alt = "Alt",
  CapsLock = "CapsLock",
  Escape = "Escape",
  Esc = "Esc",
  Space = " ",
  PageUp = "PageUp",
  PageDown = "PageDown",
  End = "End",
  Home = "Home",
  ArrowLeft = "ArrowLeft",
  ArrowUp = "ArrowUp",
  ArrowRight = "ArrowRight",
  ArrowDown = "ArrowDown",
  Left = "Left",
  Up = "Up",
  Right = "Right",
  Down = "Down",
  Insert = "Insert",
  Delete = "Delete",
  Zero = "0",
  ClosedParen = ")",
  One = "1",
  ExclamationMark = "!",
  Two = "2",
  AtSign = "@",
  Three = "3",
  PoundSign = "£",
  Hash = "#",
  Four = "4",
  DollarSign = "$",
  Five = "5",
  PercentSign = "%",
  Six = "6",
  Caret = "^",
  Seven = "7",
  Ampersand = "&",
  Eight = "8",
  Asterisk = "*",
  Nine = "9",
  OpenParen = "(",
  A = "A",
  B = "B",
  C = "C",
  D = "D",
  E = "E",
  F = "F",
  G = "G",
  H = "H",
  I = "I",
  J = "J",
  K = "K",
  L = "L",
  M = "M",
  N = "N",
  O = "O",
  P = "P",
  Q = "Q",
  R = "R",
  S = "S",
  T = "T",
  U = "U",
  V = "V",
  W = "W",
  X = "X",
  Y = "Y",
  Z = "Z",
  Meta = "Meta",
  F1 = "F1",
  F2 = "F2",
  F3 = "F3",
  F4 = "F4",
  F5 = "F5",
  F6 = "F6",
  F7 = "F7",
  F8 = "F8",
  F9 = "F9",
  F10 = "F10",
  F11 = "F11",
  F12 = "F12",
  NumLock = "NumLock",
  ScrollLock = "ScrollLock",
  SemiColon = ";",
  Equals = "=",
  Comma = ",",
  Dash = "-",
  Period = ".",
  UnderScore = "_",
  PlusSign = "+",
  ForwardSlash = "/",
  Tilde = "~",
  GraveAccent = "`",
  OpenBracket = "[",
  ClosedBracket = "]",
  Quote = "'",
}

export enum ActionType {
  Script = "script",
  Text = "text",
  File = "file",
  Ai = "ai",
}

export type ActionParams = string | number | boolean | object;

export type ShortcutProps = {
  id: string;
  name: string;
  accelerator: string;
  actionType: string;
  actionDetails: Record<string, ActionParams> | undefined;
};

export const keyMap: { [key: string]: Key } = {
  'Control': Key.Ctrl, 'Shift': Key.Shift, 'Alt': Key.Alt, 'Meta': Key.Meta, // Modifiers
  'a': Key.A, 'b': Key.B, 'c': Key.C, 'd': Key.D, 'e': Key.E, 'f': Key.F, 'g': Key.G, 'h': Key.H, 'i': Key.I, 'j': Key.J, 'k': Key.K, 'l': Key.L, 'm': Key.M, 'n': Key.N, 'o': Key.O, 'p': Key.P, 'q': Key.Q, 'r': Key.R, 's': Key.S, 't': Key.T, 'u': Key.U, 'v': Key.V, 'w': Key.W, 'x': Key.X, 'y': Key.Y, 'z': Key.Z,
  'A': Key.A, 'B': Key.B, 'C': Key.C, 'D': Key.D, 'E': Key.E, 'F': Key.F, 'G': Key.G, 'H': Key.H, 'I': Key.I, 'J': Key.J, 'K': Key.K, 'L': Key.L, 'M': Key.M, 'N': Key.N, 'O': Key.O, 'P': Key.P, 'Q': Key.Q, 'R': Key.R, 'S': Key.S, 'T': Key.T, 'U': Key.U, 'V': Key.V, 'W': Key.W, 'X': Key.X, 'Y': Key.Y, 'Z': Key.Z,
  '0': Key.Zero, '1': Key.One, '2': Key.Two, '3': Key.Three, '4': Key.Four, '5': Key.Five, '6': Key.Six, '7': Key.Seven, '8': Key.Eight, '9': Key.Nine,
  'Enter': Key.Enter, 'Escape': Key.Escape, ' ': Key.Space, 'Tab': Key.Tab,
  'ArrowUp': Key.ArrowUp, 'ArrowDown': Key.ArrowDown, 'ArrowLeft': Key.ArrowLeft, 'ArrowRight': Key.ArrowRight,
};
